### ISSUE TITLE
v1.2 support incomplete

### ISSUE THREAD

**Issue by tpoppins** [chocolate-doom/chocolate-doom#1223]
This is related to #1205 - big thanks to @SmileTheory for the work! - we're almost there.

Tested with today's daily build as well as Crispy (cf. [fabiangreffrath#500](https://github.com/fabiangreffrath/crispy-doom/pull/500)).

**Case 1**
[1_ON_1.WAD](https://www.doomworld.com/idgames/levels/doom/0-9/1_on_1) with the accompanying v1.2 demo

cmdline
-iwad doom.wad -file 1_ON_1.WAD -playdemo 1_ON_1 -gameversion 1.2

Observed behavior:
Sectors 305 and 308 -- segments (second from the south) of the walkways over the nukage that lead to the BFG in the south - fail to rise. 

Expected behavior:
Sectors 305 and 308 are supposed to rise to the level of the adjacent walkway segments, the way it works in the v1.2 vanilla. Prb+ doesn't emulate this 100% (they rise slightly higher), yet plays the demo successfully to the end.

**Case 2**
The exit bridge (sector 232) on [RETURN01](https://www.doomworld.com/idgames/levels/doom/p-r/return01) E1M2 and my old [v1.2 UV Max](http://doomedsda.us/col159.html).  

These are the only two troublesome v1.2 demos I've encountered out of a couple dozen tested so far. The two issues are similar but not the same. In the RETURN01 case there is no higher floor adjacent to the target sector; in the 1_ON_1 case there are two sets of four sectors, each daisy-chained, and the northernmost and southernmost of the sectors do have higher-floor neighbors. 

Here's a diagram of the area in question:
[link](https://i.postimg.cc/5N9b8dL7/1-ON-1-walkway.png)

The switch (S1) is tagged to the sector pairs 1, 2 and 3. The fourth pair is tagged to another switch (S2), in the secret next to the Cybers in the east. The red numbers are the floor heights. 

In v1.9 and current v1.2 compat implementation, sector pairs 1 and 4 always rise; sector pair 3 (i.e., the above-mentioned sectors 305 and 308) only if S2 is activated before S1. Sector pair 2 never rises.
In **vanilla v1.2** all the tagged sectors rise to -20 when the corresponding switches are activated, regardless of the order of switch activation.

_P_FindNextHighestFloor_ is the prime suspect, naturally; but I'd also like to point out the following code from Prboom-plus' [p_spec.c](https://svn.prboom.org/repos/branches/prboom-plus-24/prboom2/src/p_spec.c):486:

```
  /* cph - my guess at doom v1.2 - 1.4beta compatibility here.
   * If there are no higher neighbouring sectors, Heretic just returned
   * heightlist[0] (local variable), i.e. noise off the stack. 0 is right for
   * RETURN01 E1M2, so let's take that. */
  return (compatibility_level < doom_1666_compatibility ? 0 : currentheight);
```

This part seems to have been overlooked during the cribbing process. ;) I suspect there might be more as it's not readily apparent how that code would help in the 1_ON_1 case.

**Comment by tpoppins** [comment]
The background for the above code (Colin Phipps' thread on DW):
https://www.doomworld.com/forum/topic/36337-return01/?do=findComment&comment=603575

**Comment by SmileTheory** [comment]
So I improvised my own fix that does approximately the right thing in 1_ON_1.WAD and seems to still work on RETURN01 E1M2. ( https://github.com/chocolate-doom/chocolate-doom/pull/1207/commits/5b4f916d7e9cec42aa778de099d1c8ec9b777938 )

I committed it as part of my v1.0/v1.1 pull request, though, so hopefully that gets in sooner rather than later. :)

**Comment by tpoppins** [comment]
Well-done! RETURN01 E1M2 now works perfectly, 1_ON_1 nearly so.

Three minor issues remain outstanding.

1. Lost Souls should count toward the Kills percentage.
2. On 1_ON_1 sectors 306 and 309 rise slightly (not enough to desync 1_ON_1.LMP) higher than -20. That happens to their southerly neighbors, sectors 305 and 308, as well when the switch nearby is activated _before_ the switch next to the Cybers.
3. [VILLAGE](https://www.doomworld.com/idgames/levels/doom/v-z/village) and [TOWN](https://www.doomworld.com/idgames/levels/doom/s-u/town) rely on the on the old (pre-1.4-beta) behavior of linedef special 98 (WR Floor lower to 8 above highest adjacent floor) to create dynamic circular staircases that build as the player circles over them. In both levels these staircases give access to the first key (red in the former, yellow in the latter case). 
Now both WADs work -- viz my v1.2-format demos for [WADPAK2](http://doomedsda.us/wad1082.html) and [WADPAK4](http://doomedsda.us/wad1985.html) -- the emulation is not 100% accurate, though: in the v1.2 vanilla the sectors rise silently, in the emulation mode they make noise (DSPSTOP).

Other than that the v1.2 emulation is looking good. After testing a few dozen demos I have yet to find out that desyncs due to inadequate emulation, apart from some WADs (e.g. old FOREST versions) where the author updated a map but failed to update the demo.

**Comment by SmileTheory** [comment]
> 
>     1. Lost Souls should count toward the Kills percentage.

They don't?  This is part of the 1.0/1.1 patch, as of https://github.com/chocolate-doom/chocolate-doom/pull/1207/commits/a65b3fb7e608892287b9795931b5e26a65841a53 .  It's probably missing in the master branch, though.

>     2. On 1_ON_1 sectors 306 and 309 rise slightly (not enough to desync 1_ON_1.LMP) higher than -20. That happens to their southerly neighbors, sectors 305 and 308, as well when the switch nearby is activated _before_ the switch next to the Cybers.

I don't get this in my testing either, they raise to exactly -20, regardless of the switch order.  Admittedly my testing was limited to noclipping through the map and hitting switches though, I didn't want to sit through most of 1_ON_1.LMP. :)

>     3. [VILLAGE](https://www.doomworld.com/idgames/levels/doom/v-z/village) and [TOWN](https://www.doomworld.com/idgames/levels/doom/s-u/town) rely on the old (pre-1.4-beta) behavior of linedef special 98 (WR Floor lower to 8 above highest adjacent floor) to create dynamic circular staircases that build as the player circles over them. In both levels these staircases give access to the first key (red in the former, yellow in the latter case).
>         Now both WADs work -- viz my v1.2-format demos for [WADPAK2](http://doomedsda.us/wad1082.html) and [WADPAK4](http://doomedsda.us/wad1985.html) -- the emulation is not 100% accurate, though: in the v1.2 vanilla the sectors rise silently, in the emulation mode they make noise (DSPSTOP).

I'll look into this one.

**Comment by tpoppins** [comment]
Thank you for pointing to [a65b3fb](https://github.com/chocolate-doom/chocolate-doom/commit/a65b3fb7e608892287b9795931b5e26a65841a53), that solves point 1 nicely.

Scratch point 2 too -- it was a copy&paste error on my part. I left out a statement, and that not only led to the above-mentioned anomaly on 1_ON_1 but also broke the internal v1.2 DEMO1 in [DTH1](https://www.doomworld.com/idgames/levels/doom/d-f/dth1). After correcting this oversight everything plays back properly now: 1_ON_1, RETURN01 E1M2 and DTH1. 

Incidentally, prb+ desyncs on that DTH1 demo in the same spot, so that part of its p_spec.c should be reworked à la Choco.

**Comment by fabiangreffrath** [comment]
> Incidentally, prb+ desyncs on that DTH1 demo in the same spot, so that part of its p_spec.c should be reworked à la Choco.

Do you say that there is a bug in PrBoom+ that needs to get fixed?

**Comment by tpoppins** [comment]
Yes: the internal DEMO1 @DTH1.WAD desyncs in latest test, and it's a minor marvel that 1_ON_1,LMP doesn't as well (the walkways segments rise too high, see above). SmileTheory's fix is obviously more comprehensive.

The question is who is going to push it through. Last prboom-plus fix was almost three years ago. If RjY still has his grandfathered access to the repo perhaps he could do it.

**Comment by tpoppins** [comment]
@drfrag666: I have trouble compiling RUDE-Doom. My email is tpoppins at juno dot com. 
Sorry for OT, the RUDE-Doom repo doesn't appear to have an Issues section and there's no contact info.

**Comment by fabiangreffrath** [comment]
There is an "active" fork of prboom-plus available maintained by @coelckers at https://github.com/coelckers/prboom-plus . Would be great if you could file a PR there.

**Comment by tpoppins** [comment]
Thank you for the headsup, Fabian; I had no idea there was a (semi-)active prb+ fork under development. I opened a new issue (autolinked above). My knowledge of C and DOOM's code being rudimentary I wouldn't entertain the idea of submitting a PR unless it were something very simple and straightforward.
