### ISSUE TITLE
High DPI display scaling on win8.1

### ISSUE THREAD

**Issue by fx02** [chocolate-doom/chocolate-doom#598]
Since I've upgraded to win 8.1 I have to use compatibility options on chocolate-doom.exe to make it work properly. Any chance to get that issue fixed?
![choco](https://cloud.githubusercontent.com/assets/2067180/9424335/013393d8-48e9-11e5-95bb-2fc5f6aaafea.jpg)

**Comment by fragglet** [comment]
That's unfortunate :(  Working well with highdpi is quite important. Does it make any difference in fullscreen vs. windowed, directx vs. windib, etc.?

Not having any kind of functioning Windows install available to debug with means I'm limited in what I can do.

Maybe there's a manifest compatibility option we can turn on to prevent this happening.

**Comment by fragglet** [comment]
Actually, this was supposed to have been fixed 2 years ago in 5a8db1512bf95325d466086498b20474b769924f - I wonder why this has come back?

**Comment by fragglet** [comment]
These are the shipped 2.2.0 binaries downloaded from the website that you're using, right? Not your own builds?

**Comment by fx02** [comment]
Dunno really, I think it's some build from your site, will try new one right now...
Nope, tried clean 2.2.0 to be 100% sure and the problem is still here. 
With windib (blank) it's still oversized (see screenshot) but centered.
Even setup is not centered on screen.
![windib](https://cloud.githubusercontent.com/assets/2067180/9448952/d9165d50-4a9f-11e5-8ec5-4fdf698af035.jpg)

**Comment by bb010g** [comment]
Could you give more info on your drivers?

**Comment by fx02** [comment]
Card is nvidia gtx 750, nvidia drivers 353.82, OS win8.1 pro. Anything else?
![video settings1](https://cloud.githubusercontent.com/assets/2067180/9475923/fa36743c-4b69-11e5-9c5e-80f5bdedb01e.jpg)
![video settings2](https://cloud.githubusercontent.com/assets/2067180/9475924/fa3ce89e-4b69-11e5-803e-c31a5912b1d1.jpg)

**Comment by haleyjd** [comment]
In my experience it's the "change the size of all items" setting that tends to screw with SDL 1.2.x games in this manner. We had some similar reports against SVE and the people affected all had that setting something besides "normal."

**Comment by fx02** [comment]
Solution: do not use Windows 8/8.1/10. As I found on vogons forum, the problem is that "lower" directx versions are "emulated" so that's why game runs jerky, mouse spins like crazy on higher resolutions and so on. So, SDL2 should fix this problem. This is not possible to fix with SDL1.

**Comment by fragglet** [comment]
Score another point for the SDL2 migration then.

Is "don't use the directx SDL1 video driver" also a solution?

**Comment by chungy** [comment]
> Solution: do not use Windows 8/8.1/10.

This is not a good solution, many users are unwilling or unable to change their operating system, and it's unreasonable to ask them to do so just to play Doom.

> Is "don't use the directx SDL1 video driver" also a solution?

fx02 did mention issues occurred with both windib and directx, rather sadly. Maybe he should try a sdl2-branch build and see how that runs?

**Comment by fx02** [comment]
It works OK if resolution is low eg. 640x480 on directx, windib works too on low resolutions but it's jerky/slow and I need 1920x1080 for YT recording so I use dual boot to w7.
Any sdl2 builds around? No time to mess around building, unfortunately.

**Comment by chungy** [comment]
No problem. I thought there was one, but I couldn't find it on the wiki. Just built this: https://dl.dropboxusercontent.com/u/13513277/doom/chocolate-doom-sdl2_2.2.0-146-g123eeaf.zip

**Comment by fx02** [comment]
Oh yes, this works like magic and without any problem, fast, smooth, really nice.
Now I'm thrilled, and doh... must...merge this to cndoom. But will try how it works on older systems too.

**Comment by fragglet** [comment]
If you're considering merging sdl2-branch into cndoom I'd discourage you. It's not finished yet.

**Comment by chungy** [comment]
Indeed, but it's nice to hear that SDL2 resolves the problem. Maybe, hopefully, it'll be part of the next major release :D

**Comment by fx02** [comment]
Nah, just thinking about creating branch so I can test and adjust everything.

**Comment by jmtd** [comment]
Closing since sdl2-branch fixes it.
